#
# Makefile
#
# Computer Science 50
# Problem Set 3
#

tic-tac-toe: tic-tac-toe.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o tic-tac-toe tic-tac-toe.c -lcs50 -lm

clean:
	rm -f *.o a.out core tic-tac-toe log.txt